Enable app startup with DJANGO_API feature flag set
dandi/dandiarchive pull request #590
Opened 2021-03-10 16:39 UTC by waxlamp

Even with the DJANGO_API feature flag set to `true` in the source code, the app will not correctly start up in dev without both a Girder and a Django server running. This is because the app startup routine was unconditionally asking for login status from both servers. This PR uses the feature flag to hit one or the other of the two servers.

2021-03-10 16:54 UTC, AlmightyYakob commented
This LGTM and I can't find anywhere in the code where `girderRest` is used when `DJANGO_API` is enabled _except_ right here:

https://github.com/dandi/dandiarchive/blob/12120b29a20a23991689bdb52d02753c0d62aa86/web/src/views/UserRegisterView/UserRegisterView.vue#L45

You can also see this by going to the gui beta depoyment register [page](https://gui-beta-dandiarchive-org.netlify.app/#/user/register) and looking at the network tab.

I suspect this is a bug, and should be changed to use dandi-api somehow. @dchiquito can you confirm this?

2021-03-11 16:16 UTC, dchiquito requested changes
I actually fixed this [here](https://github.com/dandi/dandiarchive/commit/8057c0b9c88c79a5118c8d40dc143fb96044b2e2), but kept that in the `django-api` branch instead of merging it into master and rebasing it. I did not realize how disruptive it was.

My solution is functionally identical to this, but I'm pretty sure it will cause merge errors when `django-api` is rebased onto this. I will clean it up momentarily.

2021-03-11 16:22 UTC, dchiquito commented
https://github.com/dandi/dandiarchive/pull/593 should fix the problem with no merge/rebase conflicts.

2021-03-11 16:28 UTC, dchiquito commented
@AlmightyYakob I think you are correct. I think it's still working in production because Girder 3 and Django are using the same GitHub OAuth application, so registering with one also registers you with the other. It's definitely a bug that needs to be fixed for migration though. Good catch

2021-03-11 19:53 UTC, waxlamp commented
Closing in favor of #593.

2021-03-11 19:53 UTC, closed without merging